# Generated by Django 4.0 on 2021-12-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
    ]
