# Generated by Django 4.0 on 2021-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_library', '0002_remove_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='cinema_genres', to='film_library.Cinema'),
        ),
    ]
